/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import eg.edu.alexu.csd.oop.game.GameEngine;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author utd
 */
public class Main_Menu extends javax.swing.JFrame {

    
    private final Timer colorTimer;
    private int colorIndex;
    
    
     public Main_Menu() {
        initComponents();

        
        colorTimer = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cycleFontColor(jLabel1);
            }
        });
        colorTimer.start();
    }

     private void cycleFontColor(JLabel label) {
        Color[] colors = {Color.GREEN,Color.ORANGE,Color.white,Color.BLACK};
        label.setForeground(colors[colorIndex]);
        colorIndex = (colorIndex + 1) % colors.length;
    }
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easybutton = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        meduim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        easybutton.setBackground(new java.awt.Color(0, 204, 204));
        easybutton.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        easybutton.setForeground(new java.awt.Color(51, 51, 51));
        easybutton.setText("easy");
        easybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(easybutton);
        easybutton.setBounds(200, 190, 80, 53);

        hard.setBackground(new java.awt.Color(153, 51, 0));
        hard.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        hard.setForeground(new java.awt.Color(0, 0, 0));
        hard.setText("hard");
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });
        getContentPane().add(hard);
        hard.setBounds(180, 310, 122, 52);

        meduim.setBackground(new java.awt.Color(255, 153, 51));
        meduim.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        meduim.setForeground(new java.awt.Color(51, 51, 51));
        meduim.setText("meduim");
        meduim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meduimActionPerformed(evt);
            }
        });
        getContentPane().add(meduim);
        meduim.setBounds(190, 250, 102, 53);

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to our Circus World");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 420, 90);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNGS/mainmenu.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
        startGameWithDifficulty(new Hard());
    }//GEN-LAST:event_hardActionPerformed

    private void meduimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meduimActionPerformed
        startGameWithDifficulty(new Meduim());
    }//GEN-LAST:event_meduimActionPerformed

    private void easybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easybuttonActionPerformed
        startGameWithDifficulty(new Easy());
    }//GEN-LAST:event_easybuttonActionPerformed

    
    private void startGameWithDifficulty(Strategy speedStrategy) {
    MyWorld.getInstance();
   ((MyWorld)MyWorld.getInstance()).setFallingSpeed(speedStrategy);
    final GameEngine.GameController gameController = GameEngine.start("Circus Of Plates", MyWorld.getInstance());
    setVisible(false);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easybutton;
    private javax.swing.JButton hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meduim;
    // End of variables declaration//GEN-END:variables
}
